name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4

    - name: install npm packages
      run: npm install

    - name: set up JDK 21
      uses: actions/setup-java@v3.14.1
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: gradle

    - name: install android sdk
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 12266719

    - name: set up ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d

    - name: Grant execute permission for gradlew
      run: cd android && chmod +x ./gradlew
    - name: Build with Gradle
      run: cd android && ./gradlew build --warning-mode fail 
    
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: app/build/outputs/apk/release/app-release.apk


